baseurl = "https://www.analyticallythinking.com/"
languageCode = "en-us"
title = "Analytically Thinking"
# Enable comments by entering your Disqus shortname
disqusShortname = "analyticallythinking"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-123750366-1"
# Define the number of posts per page
paginate = 5
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"
# Comment the themesDir option if you use this theme in production

#ignore suggested files blogdown book suggests to as blogdown does not need to complie these files
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:day/:month/:year/:slug"


[params]
    # Tell me who you are
    author = "Josh Brown"
    bio = "Georgia Tech Grad - Thinker - Sports Enthusiast"
    location = "Atlanta, GA"
    site_description = "A sports analytics blog pertaining to strategy, stats, and visualizations"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "avatar.jpg"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = ""
    logo = "ATlogo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "01-02-2006"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"
    

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/ATJoshBrown"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "analyticallythinking"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "joshbrown21"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "ATJoshBrown"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = false
